# Generated by Django 2.1.4 on 2018-12-20 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temas',
            fields=[
                ('tema_text', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('perguntas_tema', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Perguntas')),
            ],
            options={
                'db_table': 'temas',
            },
        ),
    ]
