# Generated by Django 2.1.4 on 2019-01-08 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_perguntas_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntas',
            name='tema',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perguntas_tema', to='temas.Temas'),
        ),
    ]
