# Generated by Django 2.1.4 on 2018-12-17 18:39

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('polls', '0002_auto_20181217_1531'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='perguntas',
            table='perguntas',
        ),
    ]
