# Generated by Django 2.1.4 on 2019-05-16 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opcoes', '0003_remove_opcoes_pergunta'),
        ('polls', '0003_auto_20190108_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='perguntas',
            name='opcoes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='opcoes.Opcoes'),
        ),
    ]
