# Generated by Django 2.1.4 on 2018-12-17 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opcoes', '0003_remove_opcoes_pergunta'),
        ('polls', '0003_auto_20181217_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='perguntas',
            name='opcoes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='opcoes.Opcoes'),
        ),
    ]
