# Generated by Django 2.1.4 on 2018-12-17 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opcoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='opcoes',
            table='opcoes',
        ),
    ]
